application: miniface
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /photos
  static_dir: photos

- url: /jscss
  static_dir: jscss

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /signup
  script: main.app
  secure: always

- url: /login
  script: main.app
  secure: always

- url: /forgot
  script: main.app
  secure: always

- url: .*
  script: main.app


libraries:
- name: webapp2
  version: "2.5.1"
